name: TuTienCultivation
main: me.tutien.cultivation.TuTienCultivation
version: 1.0
api-version: 1.21

commands:
  tutien:
    description: Bắt đầu tu tiên
  tuluyen:
    description: Tu luyện linh khí
  dotpha:
    description: Đột phá cảnh giới
